# Generated by Django 4.2.23 on 2025-08-23 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Mã thuốc", max_length=50, unique=True),
                ),
                ("name", models.CharField(help_text="Tên thuốc", max_length=200)),
                (
                    "generic_name",
                    models.CharField(help_text="Tên hoạt chất", max_length=200),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, help_text="Tên thương mại", max_length=200
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Viên nén"),
                            ("CAPSULE", "Viên nang"),
                            ("SYRUP", "Siro"),
                            ("INJECTION", "Tiêm"),
                            ("CREAM", "Kem bôi"),
                            ("OINTMENT", "Thuốc mỡ"),
                            ("DROPS", "Thuốc nhỏ mắt/tai/mũi"),
                            ("SPRAY", "Xịt"),
                            ("POWDER", "Bột"),
                            ("SUPPOSITORY", "Viên đặt"),
                        ],
                        help_text="Dạng bào chế",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Hàm lượng (VD: 500mg, 10ml)", max_length=100
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("TABLET", "Viên"),
                            ("CAPSULE", "Viên nang"),
                            ("BOTTLE", "Chai"),
                            ("BOX", "Hộp"),
                            ("TUBE", "Tuýp"),
                            ("VIAL", "Lọ"),
                            ("AMPOULE", "Ống thuốc tiêm"),
                            ("SACHET", "Gói"),
                            ("ML", "ml"),
                            ("MG", "mg"),
                            ("G", "g"),
                        ],
                        help_text="Đơn vị tính",
                        max_length=20,
                    ),
                ),
                ("indication", models.TextField(help_text="Chỉ định sử dụng")),
                (
                    "contraindication",
                    models.TextField(blank=True, help_text="Chống chỉ định"),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Tác dụng phụ"),
                ),
                (
                    "interactions",
                    models.TextField(blank=True, help_text="Tương tác thuốc"),
                ),
                (
                    "dosage_adult",
                    models.TextField(blank=True, help_text="Liều dùng người lớn"),
                ),
                (
                    "dosage_child",
                    models.TextField(blank=True, help_text="Liều dùng trẻ em"),
                ),
                (
                    "storage_condition",
                    models.TextField(blank=True, help_text="Điều kiện bảo quản"),
                ),
                (
                    "expiry_after_opening",
                    models.IntegerField(
                        blank=True, help_text="Hạn sử dụng sau khi mở (ngày)", null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, help_text="Đơn giá (VNĐ)", max_digits=10
                    ),
                ),
                (
                    "insurance_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Giá BHYT (VNĐ)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, help_text="Tồn kho hiện tại"),
                ),
                (
                    "minimum_stock",
                    models.IntegerField(default=10, help_text="Tồn kho tối thiểu"),
                ),
                (
                    "maximum_stock",
                    models.IntegerField(default=1000, help_text="Tồn kho tối đa"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, help_text="Số đăng ký thuốc", max_length=50
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(help_text="Nhà sản xuất", max_length=200),
                ),
                (
                    "country_of_origin",
                    models.CharField(help_text="Nước sản xuất", max_length=100),
                ),
                (
                    "is_prescription_required",
                    models.BooleanField(default=True, help_text="Cần đơn thuốc"),
                ),
                (
                    "is_controlled_substance",
                    models.BooleanField(
                        default=False, help_text="Thuốc kiểm soát đặc biệt"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thuốc",
                "verbose_name_plural": "Thuốc",
                "db_table": "drugs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_number", models.CharField(max_length=30, unique=True)),
                ("prescription_date", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("OUTPATIENT", "Ngoại trú"),
                            ("INPATIENT", "Nội trú"),
                            ("EMERGENCY", "Cấp cứu"),
                            ("DISCHARGE", "Ra viện"),
                        ],
                        default="OUTPATIENT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Nháp"),
                            ("ACTIVE", "Có hiệu lực"),
                            ("PARTIALLY_DISPENSED", "Cấp thuốc một phần"),
                            ("FULLY_DISPENSED", "Đã cấp thuốc đầy đủ"),
                            ("CANCELLED", "Đã hủy"),
                            ("EXPIRED", "Hết hạn"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Chẩn đoán")),
                ("notes", models.TextField(blank=True, help_text="Ghi chú của bác sĩ")),
                (
                    "special_instructions",
                    models.TextField(blank=True, help_text="Hướng dẫn đặc biệt"),
                ),
                ("valid_from", models.DateTimeField(help_text="Có hiệu lực từ")),
                ("valid_until", models.DateTimeField(help_text="Có hiệu lực đến")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Tổng tiền thuốc (VNĐ)",
                        max_digits=12,
                    ),
                ),
                (
                    "insurance_covered_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Số tiền BHYT chi trả (VNĐ)",
                        max_digits=12,
                    ),
                ),
                (
                    "patient_payment_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Số tiền bệnh nhân trả (VNĐ)",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lịch khám liên quan (nếu có)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="appointments.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn thuốc",
                "verbose_name_plural": "Đơn thuốc",
                "db_table": "prescriptions",
                "ordering": ["-prescription_date"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Số lượng thuốc",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "dosage_per_time",
                    models.CharField(
                        help_text="Liều dùng mỗi lần (VD: 1 viên, 5ml)", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("1X_DAILY", "1 lần/ngày"),
                            ("2X_DAILY", "2 lần/ngày"),
                            ("3X_DAILY", "3 lần/ngày"),
                            ("4X_DAILY", "4 lần/ngày"),
                            ("EVERY_4H", "Mỗi 4 giờ"),
                            ("EVERY_6H", "Mỗi 6 giờ"),
                            ("EVERY_8H", "Mỗi 8 giờ"),
                            ("EVERY_12H", "Mỗi 12 giờ"),
                            ("AS_NEEDED", "Khi cần thiết"),
                            ("BEFORE_MEALS", "Trước ăn"),
                            ("AFTER_MEALS", "Sau ăn"),
                            ("WITH_MEALS", "Trong bữa ăn"),
                            ("BEDTIME", "Trước khi đi ngủ"),
                        ],
                        help_text="Tần suất dùng",
                        max_length=20,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Uống"),
                            ("TOPICAL", "Bôi ngoài da"),
                            ("INJECTION_IM", "Tiêm bắp"),
                            ("INJECTION_IV", "Tiêm tĩnh mạch"),
                            ("INJECTION_SC", "Tiêm dưới da"),
                            ("INHALATION", "Hít"),
                            ("EYE_DROPS", "Nhỏ mắt"),
                            ("EAR_DROPS", "Nhỏ tai"),
                            ("NASAL_DROPS", "Nhỏ mũi"),
                            ("RECTAL", "Đặt hậu môn"),
                            ("VAGINAL", "Đặt âm đạo"),
                        ],
                        help_text="Đường dùng thuốc",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        help_text="Số ngày sử dụng",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Hướng dẫn sử dụng chi tiết"),
                ),
                (
                    "special_notes",
                    models.TextField(blank=True, help_text="Ghi chú đặc biệt"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Đơn giá tại thời điểm kê đơn",
                        max_digits=10,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0, help_text="Thành tiền", max_digits=10
                    ),
                ),
                (
                    "quantity_dispensed",
                    models.IntegerField(default=0, help_text="Số lượng đã cấp"),
                ),
                (
                    "is_substitutable",
                    models.BooleanField(
                        default=True, help_text="Có thể thay thế thuốc tương đương"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_items",
                        to="prescriptions.drug",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn thuốc",
                "verbose_name_plural": "Chi tiết đơn thuốc",
                "db_table": "prescription_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDispensing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_dispensed",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, help_text="Số lô thuốc", max_length=50
                    ),
                ),
                ("expiry_date", models.DateField(help_text="Hạn sử dụng thuốc đã cấp")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ cấp thuốc"),
                            ("PREPARED", "Đã soạn thuốc"),
                            ("DISPENSED", "Đã cấp thuốc"),
                            ("RETURNED", "Đã trả lại"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("dispensed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Ghi chú khi cấp thuốc"),
                ),
                (
                    "pharmacist",
                    models.ForeignKey(
                        help_text="Dược sĩ cấp thuốc",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensed_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensing_records",
                        to="prescriptions.prescription",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensing_records",
                        to="prescriptions.prescriptionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử cấp thuốc",
                "verbose_name_plural": "Lịch sử cấp thuốc",
                "db_table": "prescription_dispensing",
                "ordering": ["-dispensed_at"],
            },
        ),
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Nhẹ"),
                            ("MODERATE", "Trung bình"),
                            ("MAJOR", "Nghiêm trọng"),
                            ("CONTRAINDICATED", "Chống chỉ định tuyệt đối"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Mô tả tương tác")),
                ("clinical_effect", models.TextField(help_text="Tác động lâm sàng")),
                ("management", models.TextField(help_text="Cách xử lý")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drug1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_drug1",
                        to="prescriptions.drug",
                    ),
                ),
                (
                    "drug2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_drug2",
                        to="prescriptions.drug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tương tác thuốc",
                "verbose_name_plural": "Tương tác thuốc",
                "db_table": "drug_interactions",
            },
        ),
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Mã nhóm thuốc", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Tên nhóm thuốc", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Mô tả nhóm thuốc"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nhóm thuốc cha (nếu có)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="prescriptions.drugcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhóm thuốc",
                "verbose_name_plural": "Nhóm thuốc",
                "db_table": "drug_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="drug",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drugs",
                to="prescriptions.drugcategory",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_drugs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "prescription_date"],
                name="prescriptio_patient_a978e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["doctor", "prescription_date"],
                name="prescriptio_doctor__a05be6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["status", "prescription_date"],
                name="prescriptio_status_e06d05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_number"], name="prescriptio_prescri_b8a9ac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginteraction",
            unique_together={("drug1", "drug2")},
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["name"], name="drugs_name_775e1b_idx"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["generic_name"], name="drugs_generic_b58053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["code"], name="drugs_code_c7f786_idx"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["category"], name="drugs_categor_8699de_idx"),
        ),
    ]
