# Generated by Django 4.2.23 on 2025-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptiondispensing",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Chưa thanh toán"),
                    ("PENDING", "Chờ cấp thuốc"),
                    ("PREPARED", "Đã soạn thuốc"),
                    ("DISPENSED", "Đã cấp thuốc"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
