# Generated by Django 4.2.23 on 2025-08-25 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="momo_deeplink",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="momo_extra_data",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="momo_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="momo_pay_url",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="momo_request_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_Amount",
            field=models.BigIntegerField(
                blank=True, help_text="Số tiền VNPAY (x100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_BankCode",
            field=models.CharField(
                blank=True, help_text="Mã ngân hàng thanh toán", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_OrderInfo",
            field=models.TextField(blank=True, help_text="Mô tả đơn hàng VNPAY"),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_PayDate",
            field=models.CharField(
                blank=True, help_text="Thời gian thanh toán VNPAY", max_length=14
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_ResponseCode",
            field=models.CharField(
                blank=True, help_text="Mã phản hồi VNPAY", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_SecureHash",
            field=models.CharField(
                blank=True, help_text="Chữ ký bảo mật VNPAY", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_TransactionNo",
            field=models.CharField(
                blank=True, help_text="Mã giao dịch ngân hàng", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vnp_TxnRef",
            field=models.CharField(
                blank=True, help_text="Mã giao dịch VNPAY", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("CASH", "Tiền mặt"), ("VNPAY", "VNPAY")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="VNPayTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vnp_TxnRef", models.CharField(max_length=50, unique=True)),
                ("vnp_Amount", models.BigIntegerField()),
                ("vnp_OrderInfo", models.TextField()),
                ("vnp_CreateDate", models.CharField(max_length=14)),
                ("vnp_IpAddr", models.GenericIPAddressField()),
                ("vnp_ResponseCode", models.CharField(blank=True, max_length=10)),
                ("vnp_TransactionNo", models.CharField(blank=True, max_length=50)),
                ("vnp_BankCode", models.CharField(blank=True, max_length=20)),
                ("vnp_PayDate", models.CharField(blank=True, max_length=14)),
                ("vnp_SecureHash", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ thanh toán"),
                            ("PAID", "Đã thanh toán"),
                            ("FAILED", "Thất bại"),
                            ("REFUNDED", "Đã hoàn tiền"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vnpay_transaction",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch VNPAY",
                "verbose_name_plural": "Giao dịch VNPAY",
                "db_table": "vnpay_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
