# Generated by Django 4.2.23 on 2025-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_momo_deeplink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="qr_code_type",
            field=models.CharField(
                blank=True, help_text="Loại QR code (VNPAY_QR, VIET_QR)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="qr_code_url",
            field=models.URLField(blank=True, help_text="URL mã QR code VNPAY"),
        ),
    ]
