# Generated by Django 4.2.23 on 2025-09-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_qr_code_type_payment_qr_code_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="qr_code_type",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="qr_code_url",
        ),
    ]
