# Generated by Django 4.2.23 on 2025-08-25 14:32

from django.db import migrations, models


def fill_missing_names(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for u in User.objects.all():
        # Đảm bảo first_name/last_name không rỗng trước khi áp constraint
        changed = False
        if u.first_name is None or u.first_name == '':
            u.first_name = u.username
            changed = True
        if u.last_name is None or u.last_name == '':
            u.last_name = '-'
            changed = True
        if changed:
            u.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_missing_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("username", ""), _negated=True),
                name="user_username_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("first_name", ""), _negated=True),
                name="user_first_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("last_name", ""), _negated=True),
                name="user_last_name_not_blank",
            ),
        ),
    ]
