# Generated by Django 4.2.23 on 2025-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_allow_null_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ward",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
