# Generated by Django 4.2.23 on 2025-09-04 03:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prescription_id",
                    models.UUIDField(
                        help_text="ID của đơn thuốc từ Prescriptions Service"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("CASH", "Tiền mặt"), ("VNPAY", "VNPAY")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="VND", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ thanh toán"),
                            ("PAID", "Đã thanh toán"),
                            ("FAILED", "Thất bại"),
                            ("REFUNDED", "Đã hoàn tiền"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "vnp_TxnRef",
                    models.CharField(
                        blank=True, help_text="Mã giao dịch VNPAY", max_length=50
                    ),
                ),
                (
                    "vnp_Amount",
                    models.BigIntegerField(
                        blank=True, help_text="Số tiền VNPAY (x100)", null=True
                    ),
                ),
                (
                    "vnp_OrderInfo",
                    models.TextField(blank=True, help_text="Mô tả đơn hàng VNPAY"),
                ),
                (
                    "vnp_ResponseCode",
                    models.CharField(
                        blank=True, help_text="Mã phản hồi VNPAY", max_length=10
                    ),
                ),
                (
                    "vnp_TransactionNo",
                    models.CharField(
                        blank=True, help_text="Mã giao dịch ngân hàng", max_length=50
                    ),
                ),
                (
                    "vnp_BankCode",
                    models.CharField(
                        blank=True, help_text="Mã ngân hàng thanh toán", max_length=20
                    ),
                ),
                (
                    "vnp_PayDate",
                    models.CharField(
                        blank=True,
                        help_text="Thời gian thanh toán VNPAY",
                        max_length=14,
                    ),
                ),
                (
                    "vnp_SecureHash",
                    models.CharField(
                        blank=True, help_text="Chữ ký bảo mật VNPAY", max_length=256
                    ),
                ),
                (
                    "qr_code_url",
                    models.URLField(blank=True, help_text="URL mã QR code VNPAY"),
                ),
                (
                    "qr_code_type",
                    models.CharField(
                        blank=True,
                        help_text="Loại QR code (VNPAY_QR, VIET_QR)",
                        max_length=20,
                    ),
                ),
                (
                    "created_by_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID của người tạo từ Auth Service",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thanh toán",
                "verbose_name_plural": "Thanh toán",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VNPayTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vnp_TxnRef", models.CharField(max_length=50, unique=True)),
                ("vnp_Amount", models.BigIntegerField()),
                ("vnp_OrderInfo", models.TextField()),
                ("vnp_CreateDate", models.CharField(max_length=14)),
                ("vnp_IpAddr", models.GenericIPAddressField()),
                ("vnp_ResponseCode", models.CharField(blank=True, max_length=10)),
                ("vnp_TransactionNo", models.CharField(blank=True, max_length=50)),
                ("vnp_BankCode", models.CharField(blank=True, max_length=20)),
                ("vnp_PayDate", models.CharField(blank=True, max_length=14)),
                ("vnp_SecureHash", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ thanh toán"),
                            ("PAID", "Đã thanh toán"),
                            ("FAILED", "Thất bại"),
                            ("REFUNDED", "Đã hoàn tiền"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vnpay_transaction",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch VNPAY",
                "verbose_name_plural": "Giao dịch VNPAY",
                "db_table": "vnpay_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=30, unique=True)),
                (
                    "cashier_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID của thu ngân từ Auth Service",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu thu",
                "verbose_name_plural": "Phiếu thu",
                "db_table": "payment_receipts",
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["prescription_id"], name="payments_prescri_5cf60f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_created_e3a130_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["vnp_TxnRef"], name="payments_vnp_Txn_d926c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vnpaytransaction",
            index=models.Index(
                fields=["vnp_TxnRef"], name="vnpay_trans_vnp_Txn_1d26dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vnpaytransaction",
            index=models.Index(fields=["status"], name="vnpay_trans_status_990ec9_idx"),
        ),
        migrations.AddIndex(
            model_name="vnpaytransaction",
            index=models.Index(
                fields=["created_at"], name="vnpay_trans_created_381599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(
                fields=["receipt_number"], name="payment_rec_receipt_5b8ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(
                fields=["created_at"], name="payment_rec_created_85660e_idx"
            ),
        ),
    ]
