# Generated by Django 4.2.23 on 2025-08-25 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="district",
        ),
        migrations.AlterField(
            model_name="patient",
            name="citizen_id",
            field=models.CharField(
                help_text="Số CCCD",
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CCCD phải có đúng 12 số", regex="^\\d{12}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                help_text="Tên người liên hệ khẩn cấp",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="SĐT người liên hệ khẩn cấp",
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại phải chuẩn định dạng Việt Nam và đủ 10 số",
                        regex="^(\\+84|0)[3|5|7|8|9](\\d{8})$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                help_text="Mối quan hệ với bệnh nhân",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                help_text="Số điện thoại liên lạc",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại phải chuẩn định dạng Việt Nam và đủ 10 số",
                        regex="^(\\+84|0)[3|5|7|8|9](\\d{8})$",
                    )
                ],
            ),
        ),
    ]
