# Generated by Django 4.2.23 on 2025-08-23 16:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_number", models.CharField(max_length=20, unique=True)),
                ("appointment_date", models.DateField(help_text="Ngày khám")),
                ("appointment_time", models.TimeField(help_text="Giờ khám")),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=15, help_text="Thời gian dự kiến (phút)"
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("NEW", "Khám mới"),
                            ("FOLLOW_UP", "Tái khám"),
                            ("CONSULTATION", "Tư vấn"),
                            ("CHECKUP", "Khám sức khỏe"),
                            ("EMERGENCY", "Cấp cứu"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Thường"),
                            ("NORMAL", "Bình thường"),
                            ("HIGH", "Ưu tiên"),
                            ("URGENT", "Khẩn cấp"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Đã đặt lịch"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("CHECKED_IN", "Đã check-in"),
                            ("IN_PROGRESS", "Đang khám"),
                            ("COMPLETED", "Hoàn thành"),
                            ("NO_SHOW", "Không đến"),
                            ("CANCELLED", "Đã hủy"),
                            ("RESCHEDULED", "Đã dời lịch"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("queue_number", models.IntegerField(help_text="Số thứ tự khám")),
                ("chief_complaint", models.TextField(help_text="Lý do khám chính")),
                (
                    "symptoms",
                    models.TextField(blank=True, help_text="Triệu chứng kèm theo"),
                ),
                ("notes", models.TextField(blank=True, help_text="Ghi chú thêm")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        help_text="Người đặt lịch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người xác nhận",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch hẹn khám",
                "verbose_name_plural": "Lịch hẹn khám",
                "db_table": "appointments",
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Mã khoa (VD: TIM, NOI, NGOAI)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Tên khoa", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Mô tả về khoa"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Vị trí (tầng, phòng)", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="SĐT liên hệ", max_length=15
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=100000,
                        help_text="Phí khám cơ bản (VNĐ)",
                        max_digits=10,
                    ),
                ),
                (
                    "average_consultation_time",
                    models.IntegerField(
                        default=30, help_text="Thời gian khám trung bình (phút)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Khoa/Phòng khám",
                "verbose_name_plural": "Khoa/Phòng khám",
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Số chứng chỉ hành nghề", max_length=50, unique=True
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("BACHELOR", "Bác sĩ"),
                            ("MASTER", "Thạc sĩ"),
                            ("DOCTOR", "Tiến sĩ"),
                            ("PROFESSOR", "Giáo sư"),
                        ],
                        help_text="Bằng cấp cao nhất",
                        max_length=20,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(help_text="Chuyên khoa", max_length=200),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        help_text="Số năm kinh nghiệm",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "max_patients_per_day",
                    models.IntegerField(
                        default=40, help_text="Số bệnh nhân tối đa/ngày"
                    ),
                ),
                (
                    "consultation_duration",
                    models.IntegerField(
                        default=15, help_text="Thời gian khám/bệnh nhân (phút)"
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Tiểu sử, kinh nghiệm")),
                (
                    "achievements",
                    models.TextField(blank=True, help_text="Thành tích, chứng chỉ"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="appointments.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bác sĩ",
                "verbose_name_plural": "Hồ sơ bác sĩ",
                "db_table": "doctor_profiles",
            },
        ),
        migrations.CreateModel(
            name="AppointmentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Đã đặt lịch"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("CHECKED_IN", "Đã check-in"),
                            ("IN_PROGRESS", "Đang khám"),
                            ("COMPLETED", "Hoàn thành"),
                            ("NO_SHOW", "Không đến"),
                            ("CANCELLED", "Đã hủy"),
                            ("RESCHEDULED", "Đã dời lịch"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Đã đặt lịch"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("CHECKED_IN", "Đã check-in"),
                            ("IN_PROGRESS", "Đang khám"),
                            ("COMPLETED", "Hoàn thành"),
                            ("NO_SHOW", "Không đến"),
                            ("CANCELLED", "Đã hủy"),
                            ("RESCHEDULED", "Đã dời lịch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Lý do thay đổi")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử trạng thái lịch hẹn",
                "verbose_name_plural": "Lịch sử trạng thái lịch hẹn",
                "db_table": "appointment_status_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.department",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("max_appointments", models.IntegerField(default=1)),
                ("current_appointments", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="appointments.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khung giờ khám",
                "verbose_name_plural": "Khung giờ khám",
                "db_table": "time_slots",
                "ordering": ["date", "start_time"],
                "unique_together": {("doctor", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Thứ Hai"),
                            (1, "Thứ Ba"),
                            (2, "Thứ Tư"),
                            (3, "Thứ Năm"),
                            (4, "Thứ Sáu"),
                            (5, "Thứ Bảy"),
                            (6, "Chủ Nhật"),
                        ],
                        help_text="Thứ trong tuần",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Ca sáng (7:00-11:30)"),
                            ("AFTERNOON", "Ca chiều (13:30-17:00)"),
                            ("EVENING", "Ca tối (18:00-21:00)"),
                            ("NIGHT", "Ca đêm (21:00-6:00)"),
                        ],
                        help_text="Ca làm việc",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Giờ bắt đầu")),
                ("end_time", models.TimeField(help_text="Giờ kết thúc")),
                (
                    "max_appointments",
                    models.IntegerField(default=20, help_text="Số lượt khám tối đa"),
                ),
                (
                    "appointment_duration",
                    models.IntegerField(
                        default=15, help_text="Thời gian/lượt khám (phút)"
                    ),
                ),
                ("effective_from", models.DateField(help_text="Có hiệu lực từ ngày")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="Có hiệu lực đến ngày", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="appointments.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch làm việc bác sĩ",
                "verbose_name_plural": "Lịch làm việc bác sĩ",
                "db_table": "doctor_schedules",
                "ordering": ["weekday", "start_time"],
                "unique_together": {("doctor", "weekday", "shift", "effective_from")},
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "appointment_time"],
                name="appointment_appoint_f2c2fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="appointment_patient_ee8848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "appointment_date"],
                name="appointment_doctor__4449b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="appointment_status_06f84b_idx",
            ),
        ),
    ]
